#!/bin/bash
# Installs Ruby and Bundler.
set -e

if [ "$1" = "--debug" ]; then
  shift
  PRINT_DEBUG="1"
  set -x
fi

warn() { echo "$@" >&2; }
abort() { EXPECTED_EXIT="1"; warn "$@"; exit 1; }

cleanup() {
  set +e
  if [ -n "$EXPECTED_EXIT" ]; then
    return
  fi
  warn "Error: $(basename $0) failed!"
  if [ -z "$PRINT_DEBUG" ]; then
    warn "For debugging output run:"
    warn "  $0 --debug"
    warn "If you're stuck: file an issue with debugging output at:"
    warn "  https://github.com/github/homebrew-bootstrap/issues/new"
  fi
}
trap "cleanup" EXIT

BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! which rbenv &>/dev/null; then
  warn "Error: you need to install 'rbenv' and put it in your PATH!"
  abort "https://github.com/sstephenson/rbenv#basic-github-checkout"
fi

if ! rbenv version-name &>/dev/null; then
  RUBY_REQUESTED="$(rbenv local)"
  RUBY_DEFINITION="$(ruby-build --definitions | grep "^$RUBY_REQUESTED$" || true)"

  if [ -z "$RUBY_DEFINITION" ]; then
    RUBY_DEFINITION="$BASE_PATH/ruby-definitions/$RUBY_REQUESTED"

    if ! [ -f "$RUBY_DEFINITION" ]; then
      warn  "Error: cannot find Ruby $RUBY_REQUESTED definition file at:"
      abort "$RUBY_DEFINITION"
    fi
  fi

  HOMEBREW_PREFIX="$(brew --prefix)"
  export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$HOMEBREW_PREFIX/opt/openssl"

  rbenv install --skip-existing "$RUBY_DEFINITION"
  if [ "$(rbenv exec ruby --version)" != "$(ruby --version)" ]; then
    warn  "You need to add rbenv to your .bash_profile/.bashrc/.zshrc!"
    abort "https://github.com/sstephenson/rbenv#basic-github-checkout"
  fi
fi

(which bundle &>/dev/null && bundle -v &>/dev/null) || {
  gem install bundler
  rbenv rehash
}

EXPECTED_EXIT="1"
exit 0
