#!/bin/bash
# Installs Node and NPM.
set -e

if [ "$1" = "--debug" ]; then
  shift
  PRINT_DEBUG="1"
  set -x
fi

warn() { echo "$@" >&2; }
abort() { EXPECTED_EXIT="1"; warn "$@"; exit 1; }

cleanup() {
  set +e
  if [ -n "$EXPECTED_EXIT" ]; then
    return
  fi
  warn "Error: $(basename $0) failed!"
  if [ -z "$PRINT_DEBUG" ]; then
    warn "For debugging output run:"
    warn "  $0 --debug"
    warn "If you're stuck: file an issue with debugging output at:"
    warn "  https://github.com/github/homebrew-bootstrap/issues/new"
  fi
}
trap "cleanup" EXIT

BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! which nodenv &>/dev/null; then
  warn "Error: you need to install 'nodenv' and put it in your PATH!"
  abort "https://github.com/OiNutter/nodenv#homebrew-on-mac-os-x"
fi

if ! nodenv version-name &>/dev/null; then
  NODE_REQUESTED="$(nodenv local)"
  NODE_DEFINITION="$(node-build --definitions | grep "^$NODE_REQUESTED$" || true)"

  if [ -z "$NODE_DEFINITION" ]; then
    abort  "Error: cannot find Node $NODE_DEFINITION definition!"
  fi

  nodenv install --skip-existing "$NODE_DEFINITION"
fi

if [ "$(nodenv exec node --version)" != "$(node --version)" ]; then
  warn  "You need to add nodenv to your .bash_profile/.bashrc/.zshrc!"
  abort "https://github.com/OiNutter/nodenv#basic-github-checkout"
fi

EXPECTED_EXIT="1"
exit 0
