#!/usr/bin/env ruby
# Generates and installs a project nginx configuration using erb.
require "erb"

root_configuration = ARGV.delete "--root"
if root_configuration
  http_port = 80
  https_port = 443
else
  http_port = 8080
  https_port = 8443
end

name = ARGV.shift
root = ARGV.shift

input = ARGV.shift

if !name || !root || !input
  abort "Usage: brew generate-nginx-conf [--root] <project_name> <project_root_path> <nginx.conf.erb>"
end

unless input.end_with? ".erb"
  abort "Error: #{input} is not a .erb file!"
end

root = File.expand_path root
input = File.expand_path input

data = IO.read input
conf = ERB.new(data).result
output = input.sub /.erb$/, ""
output.sub! /.conf$/, ".root.conf" if root_configuration
IO.write output, conf

if !root_configuration && !ENV["BOXEN_HOME"]
  homebrew_prefix = `brew --prefix 2>/dev/null`.chomp
  if homebrew_prefix && !homebrew_prefix.empty?
    server = "#{homebrew_prefix}/etc/nginx/servers/#{name}"
    system "ln -sf '#{File.absolute_path(output)}' '#{server}'"
    abort "Error: failed to symlink #{output} to #{server}!" unless $?.success?

    system "brew services restart nginx"
    abort "Error: failed to restart nginx!" unless $?.success?
  end
end
