---
name: CI
on:
  push:
    branches: master
  pull_request: []

jobs:
  build-default:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: "bash -n cmd/*"
    - run: "ruby -wc cmd/*.rb >/dev/null"
